### ISSUE TITLE
oEmbedPlugin and MVC as dynamic content?

### ISSUE THREAD

**Issue by wiske80** [Geta/oEmbed#2]
Hi... isn't it still possible to use oEmbedPlugin in wysiwyg?

If i try to use it i cant the following error:
Dynamic content 'oEmbedPlugin' does not support MVC
To support MVC either:
1) Implement 'EPiServer.DynamicContent.IDynamicContentView' (supports both MVC and WebForms).
2) Create a shared display template named 'oEmbedPlugin' (MVC only).
3) Implement System.Web.Mvc.IView (MVC only).

I thought i could create a oEmbedPlugin display template, but what should be in there.

**Comment by frederikvig** [comment]
I recommend using blocks instead. Dynamic content will be obsolete soon.
