### ISSUE TITLE
Working with Episerver 10

### ISSUE THREAD

**Issue by mennozl** [Geta/oEmbed#4]
While loading .NET types from "Geta.oEmbed" the following error(s) was reported:

    - System.TypeLoadException: Could not load type 'EPiServer.DynamicContent.IDynamicContent' from assembly 'EPiServer, Version=10.1.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'.

And on disassembling episerver.dll there is no IDynamicContent only IDynamicContentBase

**Comment by degborta** [comment]
Fixed in latest release 2.1.0 and available on nuget.episerver.com
