### ISSUE TITLE
Build error Geta.oEmbed 2.1.0

### ISSUE THREAD

**Issue by cappaulo** [Geta/oEmbed#6]
![latest](https://cloud.githubusercontent.com/assets/14766310/22883360/31a477f6-f1f0-11e6-82e6-9c98539e398d.png)
![2 0 1](https://cloud.githubusercontent.com/assets/14766310/22883362/35e1cc1a-f1f0-11e6-8fd1-b16620768c03.png)
![error](https://cloud.githubusercontent.com/assets/14766310/22883363/3898dbe2-f1f0-11e6-8bdd-ace15ec47638.png)

Created a new epi site, updated all NuGet packages (both the ones from the Episerver NuGet feed and the the ones from the standard NuGet feed), installed the latest 2.1.0 Geta.oEmbed NuGet package, it installs successfully but if I then build the solution I get an error. Please see attached screenshots.

By using a Git UI you can see that it modifies the StructureMap dependencies. If you reset only those chunks in Git then the solution builds successfully. But I guess you might break something else by "fixing" it this way.

Any ideas? Is that dependency of that version of StructureMap (structuremap (>= 2.6.4.1)) really necessary?

**Comment by frederikvig** [comment]
Hi
Yes, that's a bug. It shouldn't have a dependency on that old version. I'll see if i can get a fix out today.

**Comment by frederikvig** [comment]
Fixed with version 2.1.12 - keep an eye out on Episerver's NuGet feed.
