### ISSUE TITLE
oEmbedBlock.cs custom icon

### ISSUE THREAD

**Issue by cappaulo** [Geta/oEmbed#7]
Is it possible to add your own custom icon to https://github.com/Geta/oEmbed/blob/master/Geta.oEmbed/Block/oEmbedBlock.cs?

For example:

We have a block that looks like this:

```
[ContentType(DisplayName = "RawTextBlock", GUID = "FB5E8C04-BFDF-4043-8FE5-22209BA00952", Description = "Textarea that output the content raw")]
    [ImageUrl("/ui/images/Content-icons/block-rawtext.png")]
    public class RawTextBlock : BlockData
    {
        [UIHint(UIHint.LongString)]
        [Editable(true)]
        [Display(
            Name = "Raw text",
            Description = "Raw text",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual String RawText { get; set; }
    }
```

So what I would like to add to https://github.com/Geta/oEmbed/blob/master/Geta.oEmbed/Block/oEmbedBlock.cs is [ImageUrl("/ui/images/Content-icons/block-custom-icon.png")].

Is this possible?

**Comment by patkleef** [comment]
Currently, that's not supported. What you could do is override the oEmbedBlock.cs and define the ImageUrl attribute, like this: 

`[ContentType(DisplayName = "", GUID = "", Description = "")]
    [ImageUrl("icon.png")]
    public class CustomoEmbedBlock : oEmbedBlock
    {
    }`
