### ISSUE TITLE
Google Maps URL scheme not working

### ISSUE THREAD

**Issue by cappaulo** [Geta/oEmbed#8]
If you take a look here:

http://embed.ly/provider/googlemaps

You will see the supported URL schemes for Google Maps.

One of them is:

http://www.google.*/maps/*

and is the one  one of our clients would like to use.

Copy pasting a URL with that scheme in the oEmbed block doesn't work however. The map does not get rendered.

Any ideas?

This works though:

1. go to maps.google.com
2. select a location
3. click SHARE -> Share Link -> Short URL

The https://goo.gl URL scheme isn't even mentioned as a scheme on the embed.ly site.

**Comment by patkleef** [comment]
Hi @cappaulo ,

What is the full URL you want to use? (if you replace the wildcards)?

**Comment by cappaulo** [comment]
Hi @patkleef ,

Here's an example:

http://www.google.com/maps/place/Aage+Damgaard+ApS/@56.1957108,8.9710825,10z/data=!4m14!1m8!2m7!1sRestauranger!3m5!1sRestauranger!2s56.128038,+9.152316!4m2!1d9.1523164!2d56.1280378!3m4!1s0x464bbea33a6679bd:0x41c1307cfe747fdb!8m2!3d56.1535435!4d9.0181249

**Comment by patkleef** [comment]
Hi @cappaulo, pushed a new version of the package that includes a fix for the problem you reported.
